In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("/Users/rachelbozadjian/Desktop/load_data.csv")

data.columns

Index(['URL_OrigBrightfield_L', 'URL_OrigBrightfield_H', 'URL_OrigBrightfield',
       'URL_OrigRNA', 'URL_OrigMito', 'URL_OrigER', 'URL_OrigDNA',
       'URL_OrigAGP', 'Metadata_Source', 'Metadata_Batch', 'Metadata_Plate',
       'Metadata_Well', 'Metadata_Site', 'Metadata_AbsPositionZ',
       'Metadata_AbsTime', 'Metadata_BinningX', 'Metadata_BinningY',
       'Metadata_ChannelID', 'Metadata_ChannelName', 'Metadata_Col',
       'Metadata_ExposureTime', 'Metadata_FieldID',
       'Metadata_ImageResolutionX', 'Metadata_ImageResolutionY',
       'Metadata_ImageSizeX', 'Metadata_ImageSizeY',
       'Metadata_MainEmissionWavelength', 'Metadata_MainExcitationWavelength',
       'Metadata_MaxIntensity', 'Metadata_ObjectiveMagnification',
       'Metadata_ObjectiveNA', 'Metadata_PlaneID', 'Metadata_PositionX',
       'Metadata_PositionY', 'Metadata_PositionZ', 'Metadata_Row'],
      dtype='str')

In [8]:
filtered_data = data[["URL_OrigBrightfield_L", "URL_OrigBrightfield_H", "URL_OrigBrightfield", "URL_OrigRNA", "URL_OrigMito", "URL_OrigER", "URL_OrigDNA", "URL_OrigAGP", "Metadata_Source", "Metadata_Batch", "Metadata_Plate", "Metadata_Well", "Metadata_Site", "Metadata_Col", "Metadata_FieldID", "Metadata_PlaneID", "Metadata_Row"]]

more_filtered = filtered_data[filtered_data["Metadata_Well"].isin(["A03", "A04", "B03", "B04"])]

more_filtered

,URL_OrigBrightfield_L,URL_OrigBrightfield_H,URL_OrigBrightfield,URL_OrigRNA,URL_OrigMito,URL_OrigER,URL_OrigDNA,URL_OrigAGP,Metadata_Source,Metadata_Batch,Metadata_Plate,Metadata_Well,Metadata_Site,Metadata_Col,Metadata_FieldID,Metadata_PlaneID,Metadata_Row
18,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,1,3,1,1,1
19,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,2,3,2,1,1
20,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,3,3,3,1,1
21,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,4,3,4,1,1
22,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,5,3,5,1,1
23,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,6,3,6,1,1
24,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,7,3,7,1,1
25,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,8,3,8,1,1
26,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,9,3,9,1,1
27,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,1,4,1,1,1
28,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,2,4,2,1,1
29,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,3,4,3,1,1
30,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,4,4,4,1,1
31,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,5,4,5,1,1
32,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,6,4,6,1,1
33,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,7,4,7,1,1
34,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,8,4,8,1,1
35,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A04,9,4,9,1,1
234,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,1,3,1,1,2
235,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,2,3,2,1,2
236,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,3,3,3,1,2
237,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,4,3,4,1,2
238,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,5,3,5,1,2
239,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,6,3,6,1,2
240,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,7,3,7,1,2
241,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,8,3,8,1,2
242,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B03,9,3,9,1,2
243,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,1,4,1,1,2
244,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,2,4,2,1,2
245,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,3,4,3,1,2
246,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,4,4,4,1,2
247,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,5,4,5,1,2
248,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,6,4,6,1,2
249,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,7,4,7,1,2
250,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,8,4,8,1,2
251,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,9,4,9,1,2

In [9]:
longer_data = pd.melt(
    more_filtered,
    id_vars=['Metadata_Source', 'Metadata_Batch', 'Metadata_Plate', 'Metadata_Well', 
             'Metadata_Site', 'Metadata_Col', 'Metadata_FieldID', 'Metadata_PlaneID', 'Metadata_Row'],
    value_vars=['URL_OrigBrightfield_L', 'URL_OrigBrightfield_H', 'URL_OrigBrightfield', 
                'URL_OrigRNA', 'URL_OrigMito', 'URL_OrigER', 'URL_OrigDNA', 'URL_OrigAGP'],
    var_name='channel',
    value_name='path'
)

# Clean up the URL_type column to remove the 'URL_Orig' prefix
longer_data['channel'] = longer_data['channel'].str.replace('URL_Orig', '')

longer_data = longer_data.rename(columns={"Metadata_Source":"source", "Metadata_Batch":"batch", "Metadata_Plate":"plate", "Metadata_Well":"well", "Metadata_Site":"site", "Metadata_Col":"col", "Metadata_FieldID":"field_id", "Metadata_PlaneID":"plane_id", "Metadata_Row":"row"})

df_reordered = longer_data[['channel', 'path', 'source', 'batch', 'plate', 'well', 'site', 'col', 'field_id',
       'plane_id', 'row']]

df_reordered

,channel,path,source,batch,plate,well,site,col,field_id,plane_id,row
0,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,1,3,1,1,1
1,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,2,3,2,1,1
2,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,3,3,3,1,1
3,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,4,3,4,1,1
4,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A03,5,3,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...
283,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,5,4,5,1,2
284,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,6,4,6,1,2
285,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,7,4,7,1,2
286,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,8,4,8,1,2
287,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,B04,9,4,9,1,2

In [10]:
pd.DataFrame.to_csv(df_reordered, "samplesheet_test_full.csv", index=False)